### ISSUE TITLE
clientraw.txt.tmpl with some times that have spaces in them

### ISSUE THREAD

**Issue by ktrue** [gjr80/weewx-saratoga#1]
Using the clientraw.txt.tmpl from the 2.1.3 weewx-wd distribution results in some timestamps that are 'hh:mm:ss AM|PM' and should be either 'hh:mm:ss_AM}PM' in format.  The extra space before AM|PM throws off the parsing of clientraw.txt which is done by a split to array on ' '.

See direct output at https://saratoga-weather.org/weewx/WD/clientraw.txt

**Comment by gjr80** [comment]
Just looked at your linked clientraw.txt and everything looked OK to me, I don't see any 'AM' or 'PM':
```
12345 1.7 5.2 0 20.5 23 1016.9 0.0 2.3 6.1 0.0 0.0 26.1 27 -100 --- 0 0 0 0.0 -100 -100 -100 -100 -100 -100 -100 -100 -100 15 55 00 Saratoga,CA-15:55:00 0 --- 26 3 100 100 100 100 100 100 100 20.5 20.5 20.6 4.1 --- --- -0.03 1.7 0.4 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.6 1.7 1.9 3.0 2.4 2.5 2.3 11.3 -1.3 9113 26/03/2021 20.5 4.1 20.6 4.1 2.8 3.5 2.6 2.6 3.5 2.6 1.7 2.6 3.5 0.9 2.6 19.9 19.9 19.9 20.2 20.2 20.2 20.2 20.3 20.5 20.5 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 19.4 3.3 19.2 4.3 0 --- --- 0 0 0 0 0 0 0 0 0 0 621 26.4 22.6 17.7 1018.0 1011.5 11.3 13:20:00 13:20:00 18.5 2.5 5.4 -1.3 5.2 2021 0 1 -1 1 0 338 0 338 0 338 0 338 270 22 0 0 0.9 0 37.27471 -122.02295 0.0 93 23 0.0 07:14:29 0 0 0 0 0 0 26.7 15:49:40 07:14:29 --- !!C10.37S120!! 
```
Of course, I could me misunderstanding the issue you are seeeing.

**Comment by ktrue** [comment]
No, I just fixed the clientraw.txt.tmpl file so 134,135,166,174,175 now format with %H:%M:%S instead, so no more [space]AM/PM to mess up the parsing of the clientraw.txt file.  I also changed to add a field at 176 (--- for 10 Minute WindSpeed average) and 177 is now the EOF using the current WD signature ending to keep the parsers happy.
I've pushed the fixes to the main.

**Comment by gjr80** [comment]
Ah, I think I see what is going on, take 166 for example, the time of today's minimum `windchill`. It uses the tag:
```
$day.windchill.mintime.toString($addLabel=False, $localize=False)
```
The WeeWX tag system allows you to format tag output in a number of ways, the common way is to specify a format for a 'group' of observations (eg timestamps, temperatures, speeds etc) in the skin config file or` weewx.conf` and this format is then applied to all tags for that group throughout the template. That is what the above tag does. The other way is to explicitly set the format for the tag in the tag itself, so in this case something like:
```
$day.windchill.mintime.toString($useThisFormat='%H:%M:%S', $addLabel=False, $localize=False)
```
WeeWX 3.9.0 changed the precedence of report options and introduced various default formatting options in `weewx.conf`. These defaults override the values in the skin config file, `skin.conf`, and I've never updated `clientraw.txt.tmpl` to take this into account. This issue will equally affect other fields/tags in the clientraws but is probably less noticeable as numeric fields really just format to one, two or three decimal places whereas timestamps tend to default to more human readable date-time formats, in this case with AM/PM.

Given the clientraws are fixed format/fixed units I really need to remove the ability of config files to change the format. Easily done, just tedious. It will have the side benefit of forcing me to adopt the latest WeeWX tags, Tom is big on backwards compatibility so our old style tags still work but I think it is time to update.

**Comment by ktrue** [comment]
Thanks for the detailed explanation.  Looking at a 'real' clientraw.txt, the times are only %H:%M (omitting the seconds), so we should probably update that on the 5 fields I'd used $useThisFormat='%H:%M:%S' on.

**Comment by gjr80** [comment]
OK, yes we should update them. I will leave updating any clientraw.txt tags until later today my time (early morning your time) to avoid any conflicts.

Interesting doing this a second time around, when we first developed the templates in 2013 we were downloading clientraw.txt files (and testtags.php) from all over the world trying to reverse engineer what formats should be used where. Most fell into place pretty easily but the odd ones were rather difficult. Much easier this time with your input.
