### ISSUE TITLE
Problems with WEEWXtags.php

### ISSUE THREAD

**Issue by snaisen** [gjr80/weewx-saratoga#17]
I live inside the arctic circle. At this time of year the sun is below the horizon 24/7 and at the same time WEEWXtags.php stops updating

Alf

[syslog.txt](https://github.com/gjr80/weewx-saratoga/files/10251499/syslog.txt)

**Comment by gjr80** [comment]
Some of the sun rise/set arithmetic in the the `WEEWXtags.php` and `clientrawextra.txt` templates does not adequately handle cases where a day has no sun rise or sun set. I've hardened the respective code in those two templates and hopefully `WEEWXtags.php` and `clientrawextra.txt` should now generate without error. Would appreciate if you could test the updated templates before I release a new version. To use the updated templates:

1.  move aside/rename/delete the existing templates `etc/weewx/skins/WEEWXtags/WEEWXtags.php.tmpl` and `/etc/weewx/skins/Clientraw/clientrawextra.txt.tmpl`

2.  download the updated templates:
```
$ wget -P /etc/weewx/skins/WEEWXtags/ https://raw.githubusercontent.com/gjr80/weewx-saratoga/issue_17/skins/WEEWXtags/WEEWXtags.php.tmpl
$ wget -P /etc/weewx/skins/Clientraw/ https://raw.githubusercontent.com/gjr80/weewx-saratoga/issue_17/skins/Clientraw/clientrawextra.txt.tmpl
```
3.  no need to restart WeeW, the updated templates should be automatically used on the next report cycle

A couple of things to watch out for. There are a lot of corner cases involved; I have not necessarily tested them all so there could be some issues that arise in the future if an untested case occurs. Please let me know if this occurs. 

The other thing to watch for is any third party apps/pages that use the `WEEWXtags.php` and/or `clientrawextra.txt` data. There are some fields/variables that in some circumstances cannot be calculated if the sun never rises/sets during a day, and depending how the third party app/pages process `WEEWXtags.php` or `clientrawextra.txt` these apps/pages may encounter an error. If you have the pyephem package installed an available to WeeWX these potential problems should be avoided. Again please let me know if this occurs.

Once I hear from you that the updated templates are working I will release v0.1.5.

**Comment by snaisen** [comment]
Hi
Works fine now
Will test it for a few days ond give you feedback

Alf

**Comment by snaisen** [comment]
A line of text appears at the top of my web page
The same text also appears at the top of WEEWXtags.php and clientrawextra.txt

See attached screenshot
![image](https://user-images.githubusercontent.com/120781116/208302402-515aeac4-620d-44bc-8485-894204cb89e0.jpg)

**Comment by gjr80** [comment]
My apologies Alf, slipped into standard python comment mode and of course that does not work in a Cheetah template. Should be fixed now, try downloading the two files again and installing in place of your existing versions. Same links as above.

**Comment by snaisen** [comment]
tested a few days and it's working fine. No errors found

Alf

**Comment by gjr80** [comment]
Thanks for letting me know. I will release 0.1.5 with these fixes in the coming days and then close this issue.

You might want to make a mental note to check that that everything is OK once the sun starts rising and setting again, also when you (presumably) go to continuous sunshine in the middle of the year.

**Comment by gjr80** [comment]
v0.1.5 was released 17 January.
