### ISSUE TITLE
Add near-realtime clientraw.txt to replace the CheetaReport generated one?

### ISSUE THREAD

**Issue by ktrue** [gjr80/weewx-saratoga#3]
Can we get the realtime clientraw.txt mod installed with the weewx-saratoga plugin and replace the ClientrawReport version now creating clientraw.txt?

Also, does the rtcr work with non-Davis stations?  If not, then I think the install.py would check for Davis station before installing/replacing the existing CheetaReports generated clientraw.txt template.  That way, Davis stations would get near-realtime while other stations would get archive-interval clientraw.txt.

**Comment by gjr80** [comment]
Sure, now that we have a basic working setup we can add in rtcr. Rtcr is independent of the station, clientraw.txt is generated on receipt of every loop packet (or less frequently if desired). Bear in mind that some stations emit loop packets irregularly or at long intervals up to 60 seconds so different folks will see clientraw.txt updating at different intervals. 

Where it gets a bit tricky is with some of the stations that emit partial loop packets (ie not all observations in each loop packet). Rtcr maintains a cache to handle such stations.

I’ll work on getting rtcr integrated today and should have a working package for your Thursday morning.

**Comment by gjr80** [comment]
Have added `rtcr`, if you update to the latest weewx-saratoga GitHub commit it should run on restart. The `clientraw.txt` template should be disabled.

**Comment by ktrue** [comment]
Did the update, and it's working .. thanks!

I did add in weewx.conf a min_interval = 10 to the [[RealtimeClientraw]] so it would generate every 10 seconds.  I suggest that that be the default at installation as a 10 second update time is what is customary for Weather-Display updates.

One question:  How to get it to automatically FTP to the site after creation?  A custom skin? or something else??

Right now, it updates just fine in /var/www/weewx/html, but nothing causes CheetaGenerator to upload it until the archive interval is over.

**Comment by ktrue** [comment]
Also.. the rtcr seems to be missing the last few fields for a up-to-date clientraw.txt  (see #174-#177) in
https://saratoga-weather.org/weewx/compare-clientraw.php


174 | Time of daily max temp | 12:00_AM | !!C10.37S120!! | ❌
175 | Time of daily min temp | 7:02_AM | (missing) |  
176 | 10 minute average wind direction | 288 | (missing) |  
177 | WD Version - End of file | !!C10.37S120!! | (missing) |

**Comment by gjr80** [comment]
Will set 10 second default in the installer.

Will also add in the missing fields.

To upload the realtime `clientraw.txt` to a web server we need to use something other than the WeeWX report generation system as that will only 'act' every archive interval. What I have done in the past is have rtcr HTTP POST the file contents to a small PHP script (`post_clientraw.php`) on the web server. The PHP script saves the file contents to file on the web server. In fact, rtcr has the HTTP POST code already in there, I just forgot to set it up (plus it needed updating to handle python3). To use you need to set:
```
remote_server_url = http://web.server.address/directory/post_clientraw.php
```
under `[[RealtimeClientraw]]`. If you want to see rtcr POST debug info in the WeeWX log you can add `debug_post = True` under `[[RealtimeClientraw]]`.

On the web server you need to save `post_clientraw.php` somewhere, doesn't matter where as long as it is in the document tree. `post_clientraw.php` is in the weewx-saratoga repo under the directory named `assets` or you can wget it directly using:
```
$ wget https://raw.githubusercontent.com/gjr80/weewx-saratoga/main/assets/post_clientraw.php
```
You need to edit `post_clientraw.php` and set an appropriate path at `$cr_file`. That should be it other than a WeeWX restart.

I expect you are far more au fait with PHP than I so if there are any improvements that can be made please let me know.

I am just in the process of checking the HTTP POST code works under python2 then will add the missing fields and you should be good to go.

**Comment by gjr80** [comment]
Should be fine to install latest. Have made the follwoing chnages:

- 10 second default now in installer.
- WEEWXtags skin `[[[[Groups]]]]` removed from installer.
- HTTP POST tested and working under both python2 and python3. `post_clientraw.php` updated and included undr assets directory.
- Added new fields 174, 175 and 176. Note that field 176 is currently set to `0` until I work out the code I need to calculate 10 minute average wind direction.

**Comment by ktrue** [comment]
Outstanding, Gary!  I've installed the update and it's working on the site at 10sec intervals.

I've slightly modified the post_clientraw.php to add some data sanity checking before writing the file (to prevent miscreants from misusing the script).  Should I just commit/push that to the assets/post_clientraw.php or do a pull request for it?

I suggest a slight tweak to the preprocessing/formatting of clientraw[32] to prevent issues I've seen in the past with other stations and Weather-Display.   For the location, you should replace all '-' (dash) with '_' (underscore), then replace all ' ' (blank) with '_' (underscore) to keep the {location}-{time} format for clientraw[32].

So if the location were 'Saratoga-Weather, CA' it would use 'Saratoga_Weather,_CA' as the location in clientraw[32].  The AJAX scripts all split the field by the '-' (dash) character into location and update time and having extra '-' would break that, and extra space characters would break the split of clientraw into fields.

**Comment by gjr80** [comment]
Thanks Ken, I was always concerned that the php scripts I have used for transfer of realtime files from WeeWX to web server (I use a similar script for the SteelSeries Gauges data file) gave miscreants a point of entry to cause problems. I welcome your improvements.

I’ll have a look 32 when I am back home in front of the PC.

**Comment by ktrue** [comment]
The realtime clientraw appears to be working fine, and I've set my weewx.conf to use USA format dates (works a treat!)

**Comment by gjr80** [comment]
Commit a20b12990edbd3b27852383c87df1fad2de7d4fd reworked the field 32 format and is working well. I believe that is the final outstanding issue here so closing this.
